//! `sw-cdp1802-emulator`: RCA CDP1802 Emulator: instruction execution semantics.
//!
//! Skeleton generated by `gen-isa`. Hand-fill the per-ISA logic
//! against the trait surfaces in `sw-langtools`.

pub mod state;
pub mod memory;
pub mod exec;

